services:
    application:
        build:
            context: ./docker/app
            dockerfile: Dockerfile
            args:
                APP_ENV: '${APP_ENV:-local}'
                PHP_VERSION: '${PHP_VERSION:-8}'
                COMPOSER_VERSION: '${COMPOSER_VERSION:-2}'
                NODE_VERSION: '${NODE_VERSION:-16}'
                HOST_GID: '${HOST_GID:-1000}'
        restart: unless-stopped
        environment:
            VIRTUAL_HOST: 'app.${APP_DOMAIN:-cryptitan.local}'
            VIRTUAL_HTTP_PORT: '${APP_HTTP_PORT:-8080}'
            HOST_UID: '${HOST_UID:-1000}'
            APP_ENV: '${APP_ENV:-local}'
            APP_SCHEDULE: '${APP_SCHEDULE:-false}'
            WORK_QUEUE: ${WORK_QUEUE:-false}
            WORK_WEBSOCKET: ${WORK_WEBSOCKET:-false}
            WORK_OCTANE: ${WORK_OCTANE:-false}
        volumes:
            -   type: bind
                source: '.'
                target: '/var/www/html'
        networks:
            - neoscrypts
            - nginx-proxy
        depends_on:
            mysql:
                condition: service_healthy
            redis:
                condition: service_healthy
        healthcheck:
            test: [ "CMD-SHELL", "supervisorctl -c /var/supervisord.conf status ${NGINX_SERVER:-php-fpm} || exit 1" ]
            start_period: 10m
    nginx:
        build:
            context: ./docker/nginx
            dockerfile: Dockerfile
            args:
                NGINX_VERSION: '${NGINX_VERSION:-1}'
        stop_signal: SIGTERM
        restart: unless-stopped
        environment:
            VIRTUAL_HOST: '${APP_DOMAIN:-cryptitan.local},www.${APP_DOMAIN:-cryptitan.local}'
            VIRTUAL_HTTP_PORT: '${NGINX_HTTP_PORT:-80}'
            VIRTUAL_HTTPS_PORT: '${NGINX_HTTPS_PORT:-}'
            APP_DOMAIN: '${APP_DOMAIN:-cryptitan.local}'
            NGINX_DEFAULT_CONFIG: '${NGINX_DEFAULT_CONFIG:-/etc/nginx/conf.d/default}'
            NGINX_WEBSOCKET_CONFIG: '${NGINX_WEBSOCKET_CONFIG:-/etc/nginx/conf.d/websocket}'
            NGINX_DEFAULT_SERVER: '${NGINX_DEFAULT_SERVER:-/etc/nginx/includes/php-fpm}'
            WEBSOCKET_ENABLE: '${WEBSOCKET_ENABLE:-false}'
        volumes:
            -   type: volume
                source: 'certbot-root'
                target: '/var/www/certbot'
            -   type: volume
                source: 'letsencrypt-lib'
                target: '/var/lib/letsencrypt'
            -   type: volume
                source: 'letsencrypt'
                target: '/etc/letsencrypt'
            -   type: bind
                source: '.'
                target: '/var/www/html'
                read_only: true
        networks:
            - neoscrypts
            - nginx-proxy
        depends_on:
            application:
                condition: service_healthy
        healthcheck:
            test: [ "CMD-SHELL", "service nginx status || exit 1" ]
    mysql:
        image: 'mysql:8'
        restart: unless-stopped
        environment:
            MYSQL_DATABASE: '${DB_DATABASE:-cryptitan}'
            MYSQL_USER: '${DB_USERNAME:-cryptitan_user}'
            MYSQL_PASSWORD: '${DB_PASSWORD:-secret}'
            MYSQL_ROOT_PASSWORD: '${DB_PASSWORD:-secret}'
        volumes:
            - 'neoscrypts-mysql:/var/lib/mysql'
        networks:
            - neoscrypts
        cap_add:
            - SYS_NICE
        healthcheck:
            test: [ "CMD", "mysqladmin", "ping", "-p${DB_PASSWORD:-secret}" ]
    redis:
        build:
            context: ./docker/redis
            dockerfile: Dockerfile
            args:
                REDIS_VERSION: '${REDIS_VERSION:-6}'
        restart: unless-stopped
        volumes:
            - 'neoscrypts-redis:/data'
        networks:
            - neoscrypts
        healthcheck:
            test: [ "CMD", "redis-cli", "ping" ]
networks:
    nginx-proxy:
        external: true
        name: '${PROXY_NETWORK:-nginx-proxy}'
    neoscrypts:
        driver: bridge
volumes:
    certbot-root:
        external: true
        name: '${CERTBOT_ROOT_VOLUME:-certbot-root}'
    letsencrypt-lib:
        external: true
        name: '${LETSENCRYPT_LIB_VOLUME:-letsencrypt-lib}'
    letsencrypt-log:
        external: true
        name: '${LETSENCRYPT_LOG_VOLUME:-letsencrypt-log}'
    letsencrypt:
        external: true
        name: '${LETSENCRYPT_VOLUME:-letsencrypt}'
    neoscrypts-mysql:
        driver: local
    neoscrypts-redis:
        driver: local
    neoscrypts-pgsql:
        driver: local
